### ISSUE TITLE
node-gyp rebuild error: "`make` failed with exit code: 2"

### ISSUE THREAD

**Issue by zapk** [Rantanen/node-opus#22]
I'm unable to install node-opus for use with [discord.js](https://github.com/hydrabolt/discord.js/).
Distro: Ubuntu 16.04.1 LTS

```shell
root@ubuntu-512mb-sfo1-01:/home/bots/ivona-bot# npm install node-opus

> ref@1.3.3 install /home/bots/ivona-bot/node_modules/ref
> node-gyp rebuild

make: Entering directory '/home/bots/ivona-bot/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
binding.target.mk:94: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 4
make: Leaving directory '/home/bots/ivona-bot/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bots/ivona-bot/node_modules/ref
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN ivona-bot@1.0.0 No repository field.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-opus"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bots/ivona-bot/npm-debug.log
```

**Comment by Rantanen** [comment]
`g++: internal compiler error: Killed (program cc1plus)`

Can't really tell what is causing this by the output above.

You could try a verbose build with `npm install --verbose` (or `node-gyp rebuild --verbose` if you are building with node-gyp directly)

**Comment by zapk** [comment]
If I recall correctly, the problem was that there wasn't enough free memory
