### ISSUE TITLE
Require failed

### ISSUE THREAD

**Issue by austinhuang0131** [Rantanen/node-opus#38]
```
1|dtel     | Error: Module version mismatch. Expected 48, got 57.
1|dtel     |     at Error (native)
1|dtel     |     at Object.Module._extensions..node (module.js:597:18)
1|dtel     |     at Module.load (module.js:487:32)
1|dtel     |     at tryModuleLoad (module.js:446:12)
1|dtel     |     at Function.Module._load (module.js:438:3)
1|dtel     |     at Module.require (module.js:497:17)
1|dtel     |     at require (internal/module.js:20:19)
1|dtel     |     at bindings (/home/austin/node_modules/bindings/bindings.js:76:44)
1|dtel     |     at Object.<anonymous> (/home/austin/node_modules/node-opus/lib/OpusEncoder.js:4:34)
1|dtel     |     at Module._compile (module.js:570:32)
^C
[austin@runes ~]$ node -v
v8.0.0
[austin@runes ~]$ npm -v
5.0.0
```

**Comment by austinhuang0131** [comment]
I'll ask bindings instead

**Comment by Rantanen** [comment]
`npm install` should fix this I believe.

Node.js doesn't maintain ABI compatibility between versions. After you install a new version of Node.js, you need to recompile modules that use native code (such as node-opus).

`npm install` should recompile these.
