### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by itsariadust** [Rantanen/node-opus#52]
Trying to install node-opus but this gives me an error"
```
> node-opus@0.2.7 install C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus
> node-gyp rebuild


C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  opus.c
  opus_decoder.c
  opus_encoder.c
  opus_multistream.c
  opus_multistream_encoder.c
  opus_multistream_decoder.c
c:\users\rap\desktop\bots\erickbot\node_modules\node-opus\deps\opus\src\opus_encoder.c(655): warning C4334: '<<': result of 32-bit shift imp
licitly converted to 64 bits (was 64-bit shift intended?) [C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus\build\deps\libopus.vcxp
roj]
c:\users\rap\desktop\bots\erickbot\node_modules\node-opus\deps\opus\src\opus_encoder.c(728): warning C4334: '<<': result of 32-bit shift imp
licitly converted to 64 bits (was 64-bit shift intended?) [C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus\build\deps\libopus.vcxp
roj]
  repacketizer.c
  analysis.c
  mlp.c
  mlp_data.c
  bands.c
  celt.c
  celt_encoder.c
  celt_decoder.c
  cwrs.c
  entcode.c
  entdec.c
  entenc.c
  kiss_fft.c
  laplace.c
  mathops.c
  mdct.c
  modes.c
  pitch.c
  celt_lpc.c
  quant_bands.c
  rate.c
  vq.c
  CNG.c
  code_signs.c
  init_decoder.c
  decode_core.c
  decode_frame.c
  decode_parameters.c
  decode_indices.c
  decode_pulses.c
  decoder_set_fs.c
  dec_API.c
  enc_API.c
  encode_indices.c
  encode_pulses.c
  gain_quant.c
  interpolate.c
  LP_variable_cutoff.c
  NLSF_decode.c
  NSQ.c
  NSQ_del_dec.c
  PLC.c
  shell_coder.c
  tables_gain.c
  tables_LTP.c
  tables_NLSF_CB_NB_MB.c
  tables_NLSF_CB_WB.c
  tables_other.c
  tables_pitch_lag.c
  tables_pulses_per_block.c
  VAD.c
  control_audio_bandwidth.c
  quant_LTP_gains.c
  VQ_WMat_EC.c
  HP_variable_cutoff.c
  NLSF_encode.c
  NLSF_VQ.c
  NLSF_unpack.c
  NLSF_del_dec_quant.c
  process_NLSFs.c
  stereo_LR_to_MS.c
  stereo_MS_to_LR.c
  check_control_input.c
  control_SNR.c
  init_encoder.c
  control_codec.c
  A2NLSF.c
  ana_filt_bank_1.c
  biquad_alt.c
  bwexpander_32.c
  bwexpander.c
  debug.c
  decode_pitch.c
  inner_prod_aligned.c
  lin2log.c
  log2lin.c
  LPC_analysis_filter.c
  LPC_inv_pred_gain.c
  table_LSF_cos.c
  NLSF2A.c
  NLSF_stabilize.c
  NLSF_VQ_weights_laroia.c
  pitch_est_tables.c
  resampler.c
  resampler_down2_3.c
  resampler_down2.c
  resampler_private_AR2.c
  resampler_private_down_FIR.c
  resampler_private_IIR_FIR.c
  resampler_private_up2_HQ.c
  resampler_rom.c
  sigm_Q15.c
  sort.c
  sum_sqr_shift.c
  stereo_decode_pred.c
  stereo_encode_pred.c
  stereo_find_predictor.c
  stereo_quant_pred.c
  apply_sine_window_FLP.c
  corrMatrix_FLP.c
  encode_frame_FLP.c
  find_LPC_FLP.c
  find_LTP_FLP.c
  find_pitch_lags_FLP.c
  find_pred_coefs_FLP.c
  LPC_analysis_filter_FLP.c
  LTP_analysis_filter_FLP.c
  LTP_scale_ctrl_FLP.c
  noise_shape_analysis_FLP.c
  prefilter_FLP.c
  process_gains_FLP.c
  regularize_correlations_FLP.c
  residual_energy_FLP.c
  solve_LS_FLP.c
  warped_autocorrelation_FLP.c
  wrappers_FLP.c
  autocorrelation_FLP.c
  burg_modified_FLP.c
  bwexpander_FLP.c
  energy_FLP.c
  inner_product_FLP.c
  k2a_FLP.c
  levinsondurbin_FLP.c
  LPC_inv_pred_gain_FLP.c
  pitch_analysis_core_FLP.c
  scale_copy_vector_FLP.c
  scale_vector_FLP.c
  schur_FLP.c
  sort_FLP.c
  win_delay_load_hook.cc
  libopus.vcxproj -> C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus\build\Release\\libopus.lib
  node-opus.cc
  win_delay_load_hook.cc
c:\users\rap\desktop\bots\erickbot\node_modules\node-opus\src\node-opus.cc(41): warning C4099: 'OpusEncoder': type name first seen using 'st
ruct' now seen using 'class' [C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus\build\node-opus.vcxproj]
  c:\users\rap\desktop\bots\erickbot\node_modules\node-opus\src\node-opus.cc(41): note: see declaration of 'OpusEncoder'
C:\Users\RAP\.node-gyp\8.11.1\x64\node.lib : fatal error LNK1127: library is corrupt [C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-o
pus\build\node-opus.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\RAP\Desktop\bots\erickbot\node_modules\node-opus
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Erickbot@1.0.0 No description
npm WARN Erickbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RAP\AppData\Roaming\npm-cache\_logs\2018-04-29T02_37_05_817Z-debug.log
```
Using Windows 10, 64-bit

**Comment by Rantanen** [comment]
https://github.com/node-serialport/node-serialport/issues/912
https://github.com/node-ffi/node-ffi/issues/272#issuecomment-339242933

Seems like this is an issue with your node installation. Both of those issues seem to have been resolved by clearing some `node-gyp` temporary files etc. Can you try removing the `.node-gyp` directory under your user profile (`c:\users\rap\.node-gyp` I'd guess based on the paths in the log) and then trying the installation again?

**Comment by itsariadust** [comment]
So I reinstall node again? And sure I'll try that

**Comment by Rantanen** [comment]
Er, no. I was talking about trying the node-opus installation again.. :)

**Comment by itsariadust** [comment]
Welp, just did it and the installation went smooth
Thank you~

**Comment by Rantanen** [comment]
Glad it got resolved!
