### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Realex78** [Rantanen/node-opus#54]
Hi, I was trying to use node-opus with [discord.js](https://github.com/discordjs/discord.js) for a Discord Bot. When trying to install node-opus using `npm i node-opus`, I get this error:
```
C:\Users\alexr\Documents\GitHub\Discord Bot>npm i node-opus

> ref@1.3.5 install C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\ref
> node-gyp rebuild


C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 7, in <module>
    import copy
  File "C:\Python27\lib\copy.py", line 52, in <module>
    import weakref
  File "C:\Python27\lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alexr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\ref
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-opus@0.3.0 install C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\node-opus
> node-gyp rebuild


C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 7, in <module>
    import copy
  File "C:\Python27\lib\copy.py", line 52, in <module>
    import weakref
  File "C:\Python27\lib\weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\alexr\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alexr\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\alexr\Documents\GitHub\Discord Bot\node_modules\node-opus
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-opus@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexr\AppData\Roaming\npm-cache\_logs\2018-06-22T15_25_48_878Z-debug.log
```
I've made 2 alternative folders, re-installed Python, checking if Python is on the PATH (it is), installed [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools), and I haven't been able to install it.

**Comment by Rantanen** [comment]
Based on the discussion at https://github.com/platformio/platformio-atom-ide/issues/1298, this seems like it's a general Python problem with multiple Python installations present.

Unfortunately there's nothing I can do to fix this; You could try reporting this on [node-gyp](https://github.com/nodejs/node-gyp) or somewhere in Python issue tracker.

**Comment by Realex78** [comment]
So as you said, there were multiple Python installations on my system. I uninstalled both versions and re-installed the lastest version, then I re-installed windows-build-tools. When I tried installing node-opus again, it was successful! Thank you, I don't think I could have installed it without your help.

**Comment by CryptAlchemy** [comment]
You are a lifesaver @Realex78 !
Thank you!
