### ISSUE TITLE
packet.packet is undefined

### ISSUE THREAD

**Issue by nfriedly** [Rantanen/node-opus#6]
I'm trying this out on a raspberry pi 2 now, and it installed fine, but piping a opus file into it immediately errors with

```
/home/pi/mic/node_modules/node-opus/lib/Decoder.js:49
    var signature = header.slice( 0, 8 );
                          ^
TypeError: Cannot read property 'slice' of undefined
    at Decoder._parseHeader (/home/pi/mic/node_modules/node-opus/lib/Decoder.js:49:24)
    at Decoder._transform (/home/pi/mic/node_modules/node-opus/lib/Decoder.js:33:8)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Writable.write (_stream_writable.js:217:11)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

The [`var header = packet.packet;`](https://github.com/Rantanen/node-opus/blob/master/lib/Decoder.js#L47) line looked suspicious, so I tried changing it to just `var header = packet;` but that just got me a different error:

```
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:87:13)
    at onerror (_stream_readable.js:556:12)
    at emit (events.js:107:17)
    at Decoder._parseHeader (/home/pi/mic/node_modules/node-opus/lib/Decoder.js:51:15)
    at Decoder._transform (/home/pi/mic/node_modules/node-opus/lib/Decoder.js:33:8)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

(I think that's the "bad header" error, but you probably have to wrap it in `new Error()` to get a more useful output. FWIW, if I look at the first bit of the file as ascii, it looks like `Lavf56.18.100encoder=Lavc56.20.100 libopusOggS`)

Any thoughts?

**Comment by nfriedly** [comment]
Nevermind, I forgot that I needed to pipe it through ogg first. I might send a PR with an example or two once I get it working.
