### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by fearek** [Rantanen/node-opus#76]
It wont install on heroku
                 from ../deps/opus/src/opus.c:32:
/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                ^~~~~~~~~~
compilation terminated.
deps/libopus.target.mk:269: recipe for target 'Release/obj.target/libopus/deps/opus/src/opus.o' failed
make: *** [Release/obj.target/libopus/deps/opus/src/opus.o] Error 1
make: Leaving directory '/app/node_modules/node-opus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-1038-aws
gyp ERR! command "/app/.heroku/node/bin/node" "/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/node-opus
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by fearek** [comment]
fixed with yarn
