### ISSUE TITLE
was compiled against a different Node.js version using NODE_MODULE_VERSION 64. This version of Node.js requires NODE_MODULE_VERSION 72

### ISSUE THREAD

**Issue by stuyy** [Rantanen/node-opus#92]
No idea what's wrong. I've tried uninstalling, rebuilding, etc. nothing's working. I'm using Node version 12.11.0. I updated like 2-3 weeks ago.
i also get this error when trying to install via npm. 
![image](https://user-images.githubusercontent.com/25330491/67635151-d8a6b700-f899-11e9-956a-abe0d153a300.png)

```

Error: The module '/Users/anson/node_modules/node-opus/build/Release/node-opus.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:992:18)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/Users/anson/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/anson/node_modules/node-opus/lib/OpusEncoder.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
(node:43691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:43691) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by jsmith** [comment]
This is a late response but are you using electron? I had a similar issue and used [electron-rebuild](https://github.com/electron/electron-rebuild)!

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
