### ISSUE TITLE
Installation problem with python: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 23: ordinal not in range(128)

### ISSUE THREAD

**Issue by D3rise** [Rantanen/node-opus#96]
```
yarn add discord.js node-opus ytdl-core
yarn add v1.21.1
info No lockfile found.
[1/4] Resolving packages...
warning discord.js > snekfetch@3.6.4: use node-fetch instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > discord.js@11.5.1" has unmet peer dependency "@discordjs/uws@^10.149.0".
[4/4] Building fresh packages...
[1/2] ⠄ ref
warning Error running install script for optional dependency: "C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\ref: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\ref
Output:
C:\\Users\\deris\\���㬥���\\Projects\\runibot-radio-webinterface\\node_modules\\ref>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.14.1 | win32 | x64
gyp info find Python using Python version 2.7.17 found at \"C:\\Python27\\python.exe\"
gyp info find VS using VS2017 (15.9.28307.1000) found at:
gyp info find VS \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Python27\\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\deris\\\\Документы\\\\Projects\\\\runibot-radio-webinterface\\\\node_modules\\\\ref\\\\build\\\\config.gypi',        
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\deris\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.14.1\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\deris\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.14.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\deris\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\12.14.1\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\deris\\\\Документы\\\\Projects\\\\runibot-radio-webinterface\\\\node_modules\\\\ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\deris\\\\Документы\\\\Projects\\\\runibot-radio-webinterface\\\\node_modules\\\\ref\\\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 50, in <module>
    sys.exit(gyp.script_main())
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 554, in script_main
    return main(sys.argv[1:])
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 547, in main
    return gyp_main(args)
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 2012, in GenerateOutput
    msvs_version)
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1847, in _CreateProjectObjects  
    guid = _GetGuidOfProject(proj_path, spec)
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 914, in _GetGuidOfProject       
    guid = guid or MSVSNew.MakeGuid(proj_path)
  File \"C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\MSVSNew.py\", line 48, in MakeGuid
    d = hashlib.md5((str(seed) + str(name)).encode('utf-8')).hexdigest().upper()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 23: ordinal not in range(128)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\ref
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok"
[2/2] ⠈ node-opus
error C:\Users\deris\Документы\Projects\runibot-radio-webinterface\node_modules\node-opus: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\deris\Документы\Projects\runibot-radio-webinterface\node_modules\node-opus
Output:
C:\Users\deris\���㬥���\Projects\runibot-radio-webinterface\node_modules\node-opus>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.14.1 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "C:\Python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1000) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\node-opus\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\deris\\AppData\\Local\\node-gyp\\Cache\\12.14.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\deris\\AppData\\Local\\node-gyp\\Cache\\12.14.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\deris\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.14.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\node-opus',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\deris\\Документы\\Projects\\runibot-radio-webinterface\\node_modules\\node-opus\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2012, in GenerateOutput
    msvs_version)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1847, in _CreateProjectObjects
    guid = _GetGuidOfProject(proj_path, spec)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 914, in _GetGuidOfProject
    guid = guid or MSVSNew.MakeGuid(proj_path)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 48, in MakeGuid
    d = hashlib.md5((str(seed) + str(name)).encode('utf-8')).hexdigest().upper()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 23: ordinal not in range(128)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"  
gyp ERR! cwd C:\Users\deris\Документы\Projects\runibot-radio-webinterface\node_modules\node-opus
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

**Comment by D3rise** [comment]
Oh, alright. I fixed this by removing non-ASCII characters from directory name ( C:\Users\deris\ **Документы** \Projects\runibot-radio-webinterface )
